server:
  port: 8080
spring:
  application:
    name: greeting-service

greeting-service:
  greeting: "Hello"
  defaultValue: "World. Testing..."

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS